#  Template NodeJS build

image: node:20

pipelines:
  default:
    - step:
        script:
          - echo "Commit $BITBUCKET_COMMIT"
          - echo "Branch $BITBUCKET_BRANCH"
          - echo "TAG $BITBUCKET_TAG"
          - echo "User triggering $BITBUCKET_STEP_TRIGGERER_UUID"
    - step:
        name: Deploy artifacts using SCP to PROD        
        script:
        - pipe: atlassian/scp-deploy:0.3.3
          variables:
            USER: $USER_SNARCHIO
            SERVER: $SERVER_SNARCHIO
            EXTRA_ARGS: ["-P", "123"]
            REMOTE_PATH: '/home/atlassianci'
            LOCAL_PATH: 'src/*'          
    - step:
        name: Default Step manual
        trigger: manual
        caches:
          - node
        script:
          - npm install
          - npm run build
  branches:
    snarchio:
      - step:
          script:
            - echo "Commit $BITBUCKET_COMMIT"
            - echo "Branch $BITBUCKET_BRANCH"
            - echo "TAG $BITBUCKET_TAG"
            - echo "User triggering $BITBUCKET_STEP_TRIGGERER_UUID"
      - step:
          name: Branches Snarchio Step manual
          trigger: manual
          caches:
            - node
          script:
            - npm install
            - npm run build          
  custom:
    manual:      
      - step:
          name: Common Manual Step
          caches:
            - node
          script:
            - npm install
            - npm run build